2004-11-03  Rodney Dawes  <dobey@novell.com>
	* Makefile.am (pkgdata_DATA): Add new Makefile.in.in and remove
	all of the patches that we used to maintain for Makefile.in.in from
	glib-gettextize

	* Makefile.in.in: Add our own Makefile.in.in to install into the po
	directory that already includes the patches we had for it, and does
	not require mkinstalldirs in the local tree to install

	* intltoolize.in: Add po/Makefile.in.in to the files to copy list
	Fix the file linking/copying to use basename for the file, so that
	we can store Makefile.in.in without its own special subdir

	Fixes #144715

diff --git a/intltoolize.in b/intltoolize.in
--- a/intltoolize.in
+++ b/intltoolize.in
@@ -141,7 +141,7 @@ else
 fi
 
 
-files='intltool-extract.in intltool-merge.in intltool-update.in'
+files='intltool-extract.in intltool-merge.in intltool-update.in po/Makefile.in.in'
 
 auxdir=.
 auxdirline=`egrep '^AC_CONFIG_AUX_DIR' $configure 2>/dev/null`
@@ -235,10 +235,10 @@ for file in $files; do
   fi
 
   $rm $file
-  if test -n "$ln_s" && $ln_s $pkgdatadir/$file $file; then :
-  elif $cp $pkgdatadir/$file $file; then :
+  if test -n "$ln_s" && $ln_s $pkgdatadir/`basename $file` $file; then :
+  elif $cp $pkgdatadir/`basename $file` $file; then :
   else
-    echo "$progname: cannot copy '$pkgdatadir/$file' to '$file'" 1>&2
+    echo "$progname: cannot copy '$pkgdatadir/`basename $file`' to '$file'" 1>&2
     status=1
   fi
 done
