2005-01-20  James Henstridge  <james@jamesh.id.au>
	* intltoolize.in: if AC_CONFIG_MACRO_DIR is used in the
	configure.in file, install intltool.m4 to that macro directory.

	Fixes #160943

diff --git a/intltoolize.in b/intltoolize.in
--- a/intltoolize.in
+++ b/intltoolize.in
@@ -40,7 +40,8 @@ prefix=@prefix@
 datadir=@datadir@
 pkgdatadir=@pkgdatadir@
 
-intltool_m4="${datadir}/aclocal/intltool.m4"
+aclocaldir=${datadir}/aclocal
+intltool_m4="${aclocaldir}/intltool.m4"
 
 dry_run=no
 help="Try '$progname --help' for more information."
@@ -246,6 +247,24 @@ done
 exit $status
 # make sure this subshell exits with the exit value if it failed
 ) || exit $?
+
+
+# If the AC_CONFIG_MACRO_DIR() macro is used, copy intltool.m4 from our
+# prefix to that directory.  This makes sure that the M4 macro used
+# matches the intltool scripts we install.
+# If AC_CONFIG_MACRO_DIR is not used, things will behave as before (aclocal
+# will be used to pull in the macro.
+m4dir=`cat "$configure" | grep '^AC_CONFIG_MACRO_DIR' | sed -n -e 's/AC_CONFIG_MACRO_DIR(\([^()]*\))/\1/p' | sed -e 's/^\[\(.*\)\]$/\1/' | sed -e 1q`
+if test -n "$m4dir"; then
+  rm -f $m4dir/intltool.m4
+  if test -n "$ln_s" && $ln_s $intltool_m4 $m4dir/intltool.m4; then :
+  elif $cp $intltool_m4 $m4dir/intltool.m4; then :
+  else
+    echo "$progname: cannot copy '$intltool_m4' to '$m4dir/intltool.m4'" 1>&2
+    exit 1
+  fi
+fi
+
 
 # FIXME: This probably does not work w/ builddir != srcdir because it
 # gets at source files relative to the current directory.
